// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Stock struct {
	Symbol        string  `json:"symbol"`
	Name          string  `json:"name"`
	Price         float64 `json:"price"`
	Change        float64 `json:"change"`
	PercentChange float64 `json:"percentChange"`
	Volume        int32   `json:"volume"`
	Currency      string  `json:"currency"`
	Exchange      string  `json:"exchange"`
	UpdatedAt     string  `json:"updatedAt"`
}

type Subscription struct {
}
